# Generated by Django 3.2 on 2022-05-31 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orphanage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=12, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('open_on_weekends', models.BooleanField(default=False)),
                ('is_working', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrphanageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='happy/%Y/%m/%d/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='happy.orphanage')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
