# Generated by Django 3.1 on 2020-10-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanages',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
