# Generated by Django 3.1 on 2020-10-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlw', '0002_orphanages_opening_hours'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orphanages',
            new_name='Orphanage',
        ),
    ]
