# Generated by Django 3.1 on 2020-10-25 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlw', '0008_auto_20201024_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='orphanage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='nlw.orphanage'),
        ),
    ]
