# Generated by Django 3.1 on 2020-10-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orphanages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('instuctions', models.TextField(blank=True, null=True)),
                ('open_on_weekends', models.BooleanField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
