# Generated by Django 3.2 on 2021-06-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanage',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
