# Generated by Django 3.2 on 2021-11-19 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlw', '0002_orphanage_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrphanageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orphanage',
            name='images',
        ),
        migrations.AlterField(
            model_name='orphanage',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='orphanageimage',
            name='orphanage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='nlw.orphanage'),
        ),
    ]
