# Generated by Django 3.1 on 2020-10-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlw', '0006_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path_image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
    ]
