# Generated by Django 3.1 on 2020-10-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlw', '0009_auto_20201024_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orphanage',
            old_name='instuctions',
            new_name='instructions',
        ),
    ]
